# Generated by Django 5.0.1 on 2024-01-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate_app', '0003_rooms'),
    ]

    operations = [
        migrations.CreateModel(
            name='tenent_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('proof', models.FileField(upload_to='realestate_app/static')),
            ],
        ),
    ]
