# Generated by Django 5.0.1 on 2024-01-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate_app', '0004_tenent_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenent_profile',
            name='type',
            field=models.CharField(choices=[('Aadhaar', 'Aadhaar'), ('Voterid', 'Voterid')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
