# Generated by Django 5.0.1 on 2024-01-14 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate_app', '0005_tenent_profile_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='room_no',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
