# Generated by Django 5.0.1 on 2024-01-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate_app', '0008_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='property_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='property_type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='room_no',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
