# Generated by Django 5.0.1 on 2024-01-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate_app', '0009_booking_property_name_booking_property_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='property_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
